/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteenmanagementsystem;

import static canteenmanagementsystem.CMS.DRIVER;
import static canteenmanagementsystem.CMS.JDBC_URL;
import static canteenmanagementsystem.CMS.con;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Shubhashish Pandey
 */
public class PayAcHolder extends javax.swing.JFrame {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form PayAcHolder
     */
    public PayAcHolder(java.awt.Frame parent, boolean modal) {
        
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPayment = new javax.swing.JButton();
        jAccountHistory = new javax.swing.JButton();
        jRemainingPayment = new javax.swing.JTextField();
        jPayMoney = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jAcHolderCustomer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pay Account Holder");
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Name Of Coustmer   :-");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Remaining payment  :-");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("PayMoney(Tk)          :-");

        jPayment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPayment.setText("Payment");
        jPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentActionPerformed(evt);
            }
        });

        jAccountHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jAccountHistory.setText("Account History");
        jAccountHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAccountHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccountHistoryActionPerformed(evt);
            }
        });

        jRemainingPayment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jPayMoney.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jAcHolderCustomer.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jAcHolderCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Name" }));
        jAcHolderCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAcHolderCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAcHolderCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAcHolderCustomerFocusLost(evt);
            }
        });
        jAcHolderCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAcHolderCustomerMouseClicked(evt);
            }
        });
        jAcHolderCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcHolderCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPayment)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jAccountHistory)
                        .addGap(45, 45, 45)
                        .addComponent(cancelButton))
                    .addComponent(jRemainingPayment, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPayMoney)
                    .addComponent(jAcHolderCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jAcHolderCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRemainingPayment)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPayMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPayment)
                    .addComponent(jAccountHistory)
                    .addComponent(cancelButton))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jAcHolderCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAcHolderCustomerFocusGained
        jAcHolderCustomer.removeAllItems();
        jAcHolderCustomer.addItem("Customer Name");
        try {
            Class.forName(DRIVER);
            con=DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }

        Statement st;
        ResultSet rs;
        try {
            st=con.createStatement();
            rs=st.executeQuery("SELECT CName FROM AcHolder");
            while(rs.next())
            {
                jAcHolderCustomer.addItem(rs.getString("CName"));
            }
        } catch (SQLException ex) {

        }

        try {
            con.close();
        } catch (SQLException ex) {

        }          // TODO add your handling code here:
    }//GEN-LAST:event_jAcHolderCustomerFocusGained

    private void jAcHolderCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAcHolderCustomerFocusLost
        String AcCName = (String) jAcHolderCustomer.getSelectedItem();
        
    }//GEN-LAST:event_jAcHolderCustomerFocusLost

    private void jAcHolderCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAcHolderCustomerMouseClicked
    try {
            Class.forName(DRIVER);
            con=DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
        Statement st;
        ResultSet rs;
        try {
            st=con.createStatement();
            rs=st.executeQuery("SELECT MR FROM AcHolderMoney where CName='"+jAcHolderCustomer.getSelectedItem()+"'");
            rs.next();
            String tempp = Double.toString(rs.getDouble("MR"));
            jRemainingPayment.setText(tempp);
        } catch (SQLException ex) {
            
        }
        
    
    try {
            con.close();
        } catch (SQLException ex) {

        }  
    }//GEN-LAST:event_jAcHolderCustomerMouseClicked

    private void jAcHolderCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcHolderCustomerActionPerformed
try {
            Class.forName(DRIVER);
            con=DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
        Statement st;
        ResultSet rs;
        try {
            st=con.createStatement();
            rs=st.executeQuery("SELECT MR FROM AcHolderMoney where CName='"+jAcHolderCustomer.getSelectedItem()+"'");
            rs.next();
            String tempp = Double.toString(rs.getDouble("MR"));
            jRemainingPayment.setText(tempp);
        } catch (SQLException ex) {
            
        }
        
    
    try {
            con.close();
        } catch (SQLException ex) {

        }  
    }//GEN-LAST:event_jAcHolderCustomerActionPerformed

    private void jPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentActionPerformed
    try {
            Class.forName(DRIVER);
            con=DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
        Statement st;
        ResultSet rs;
        try
        {
        if(jPayMoney.getText().equals(null))
        {
            JOptionPane.showMessageDialog(null,"Enter Money To Pay");
        }
        else
        {
            
        try {
            st=con.createStatement();
            rs=st.executeQuery("SELECT MP,MR FROM AcHolderMoney where CName='"+jAcHolderCustomer.getSelectedItem()+"'");
            rs.next();
            double money=rs.getDouble("MP");
            money+=Double.parseDouble(jPayMoney.getText());
            double money1 =rs.getDouble("MR");
            money1-=Double.parseDouble(jPayMoney.getText());
            st.executeUpdate("update AcHolderMoney set MP="+money+",MR="+money1+" where CName='"+jAcHolderCustomer.getSelectedItem()+"'");
            JOptionPane.showMessageDialog(null,jPayMoney.getText()+" TK Added To "+jAcHolderCustomer.getSelectedItem()+" Account....");
            jAcHolderCustomer.setSelectedItem("Customer Name");
            jPayMoney.setText(null);
            jRemainingPayment.setText(null);
            
        } catch (SQLException ex) {
            
        }
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Enter Money To Pay");
        }
    try {
            con.close();
        } catch (SQLException ex) {

        } 
    }//GEN-LAST:event_jPaymentActionPerformed

    private void jAccountHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccountHistoryActionPerformed
        try
        {if(jAcHolderCustomer.getSelectedItem().equals("Customer Name"))
        {
            
            JOptionPane.showMessageDialog(null,"Please Select Name");
        }
        else
        {
            AcHistory o = new AcHistory((String) jAcHolderCustomer.getSelectedItem());
          
        }}
        catch(Exception e)
        {
         
            JOptionPane.showMessageDialog(null,"Please Select Name");   
        }
    }//GEN-LAST:event_jAccountHistoryActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayAcHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayAcHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayAcHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayAcHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PayAcHolder dialog = new PayAcHolder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    public static javax.swing.JComboBox<String> jAcHolderCustomer;
    private javax.swing.JButton jAccountHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPayMoney;
    private javax.swing.JButton jPayment;
    private javax.swing.JTextField jRemainingPayment;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
